### ISSUE TITLE
Shutdown/Stop bot after using listener

### ISSUE THREAD

**Issue by DataWorm** [pengrad/java-telegram-bot-api#152]
Hey,

I made an instance of TelegramBot and used `telegramBot.setUpdatesListener(this)`. But when I want to shutdown the application there seem to be some thread running in background. Neither `telegramBot.setUpdatesListener(null)` nor `telegramBot.removeGetUpdatesListener()` solved that. Is that a bug or how I am supposed to close the bot connection in a clean way?

Thanks for this nice library!

**Comment by pengrad** [comment]
Hi, thank you!

I'm agree that it's not a good explanation for this library but this is expected behaviour for okhttp client that used internally.
As said in OkHttpClient javadoc:  `The threads and connections that are held will be released automatically if they remain idle.`
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html
So eventually that threads will be shut down.

You can actually force it.
For that you need to build bot with custom `OkHttpClient`.
Instead of `bot = new TelegramBot("TOKEN")` call 
```java
OkHttpClient client = new OkHttpClient();
bot = new TelegramBot.Builder("TOKEN")
                .okHttpClient(client)
                .build();
```
And then when you want to stop the app
```java
client.dispatcher().executorService().shutdown();
client.connectionPool().evictAll();
```

But be careful - `This will also cause future calls to the client to be rejected.` - so you can't reuse this client after that, which should be fine in case when you shutdown whole app.

**Comment by pengrad** [comment]
@DataWorm did it help you?

**Comment by DataWorm** [comment]
Hey, sorry for the late response. I haven't found time yet to try it out. Nevertheless I assume that your examples will work just fine. Of course it would be nice to have something like this added directly into the TelegramBot but such a manual solution should be good enough for me. Thanks a lot for your help!

**Comment by bufferum7011** [comment]
Please, explain what a `bot =`
It `TelegramBotsApi bot = new TelegramBotsApi(DefaultBotSession.class);
bot.registerBot(new Bot());` ??
