### ISSUE TITLE
How to instantiate a model.Update to unit test?

### ISSUE THREAD

**Issue by lepsistemas** [pengrad/java-telegram-bot-api#215]
Hi all!

I need to instantiate a com.pengrad.telegrambot.model.Update to use in my unit tests. There's no builder nor setters for its attributes.

My production code is this simple:

```
public void handle(Update update) {
	Long chatId = update.message().chat().id();
	String text = update.message().text();
		
	SendMessage message = new SendMessage(chatId, "You typed: " + text);
	this.bot.execute(message);
}
```

Using a spy makes my code really ugly as you can see:

```
@Mock
private TelegramBot bot;

@Test
public void should_send_message() {
	Update update = spy(Update.class);
	Message message = spy(Message.class);
	Chat chat = spy(Chat.class);
	when(update.message()).thenReturn(message);
	when(message.text()).thenReturn("Hi!");
	when(message.chat()).thenReturn(chat);
	when(chat.id()).thenReturn(1L);
		
	this.entry.handle(update);
		
	SendMessage sendMessage = new SendMessage(1, "You typed: Hi!");
	verify(this.bot).execute(sendMessage);
}
```

Also this doesn't work because SendMessage has no `equals` method and I can't use `verify` to check wether my production code called execute with the right params or not.

Any hints on this?

Thanks in advance!

**Comment by pengrad** [comment]
Hey!

Yes, it's a problem indeed.
For Update you can use `BotUtils.parseUpdate("{update_id:1, message: {message_id: 111}}");`
I'm agree that's not convenient and for other classes probably have to use gson parsing.

I was actually planning to migrate the model to Kotlin data classes.
Hope this issue will get me to actually start doing this :)

What can I suggest on how to deal around this currently - you can use fakes instead of mocks, making Fake bot and Fake response:
```java
package com.pengrad.telegrambot.response;
import com.pengrad.telegrambot.model.Message;
public class FakeSendResponse extends SendResponse {
    @Override
    public Message message() {
        // creating custom message here could a problem again though
        return super.message();
    }
}
```
and then the FakeBot:
```java
class FakeBot extends TelegramBot {
    public FakeBot() {
        super("any");
    }
    @Override
    public <T extends BaseRequest<T, R>, R extends BaseResponse> R execute(BaseRequest<T, R> request) {
        return (R) new FakeSendResponse();
    }
}
```
Using fakes you can verify then that you code behave correctly based on fake bot response.

What else:
You can completely mock whole api with `MockWebServer` 
https://github.com/square/okhttp/tree/master/mockwebserver

and then create bot with mock server api url:
`new TelegramBot.Builder("token").apiUrl(mockServerUrl + "token");`

To dispatch every request you probably have to parse String body as Telegram API use 1 path for all requests.
But this will give you full control over any api method.
There some technics to take responses from json resource, which could also improve testing experience.
https://www.raywenderlich.com/10091980-testing-rest-apis-using-mockwebserver#toc-anchor-015

**Comment by lepsistemas** [comment]
Wow, thanks for the prompt answer!

Yes, I will use the fake classes in my tests as suggested. I would really like to keep my tests in a unit level instead of mocking the whole API.

A nice coincidence is that I just subscribed yesterday to Ray Wenderlich website before you mentioned it here. =D

Thank you again for the prompt answer and hints on this!

By the way, your API is amazing. Congrats for the good job.
